# Lists vs. Arrays

In [10]:
import numpy as np

In [11]:
L = [1,2,3]                 # creating python list
A = np.array([1,2,3])       # creating numpy array

In [12]:
for e in L:
    print e

1
2
3


In [13]:
for e in A:
    print e

1
2
3


In [14]:
L.append(4)        # adding element to list
L = L + [5]        # another way to add element to list
L

[1, 2, 3, 4, 5]

In [16]:
A + A              # adding two arrays element wise addition in numpy (vector addition)

array([2, 4, 6])

In [17]:
A * 2              # multiplying vector times a scalar

array([2, 4, 6])

In [20]:
A**2               # squaring a vector

array([1, 4, 9])

Something to keep in mind about numpy is that most functions act element wise. This just means that the function is applied to each element of the vector or matrix.

In [21]:
np.sqrt(A)         # taking square root of all elements in vector 

array([1.        , 1.41421356, 1.73205081])

In [22]:
np.log(A)          # element wise log

array([0.        , 0.69314718, 1.09861229])

In [23]:
np.exp(A)          # element wise exponential 

array([ 2.71828183,  7.3890561 , 20.08553692])

With numpy you can treat lists like a vector, a mathematical object. 

---
<br></br>
# Dot Products

Recall that there are two definitions of the dot product, and they are each equivalent. 

1: The first is the summation of the element wise multiplication of the two vectors:

#### $$a \cdot b = a^Tb = \sum_{d=1}^Da_db_d$$

Here $d$ is being used to index each component. Notice that the convention $a^Tb$ implies that the vectors are column vectors, which means that the result is a (1 x 1), aka a scalar. 

2: The second is the magnitude of $a$, times the magnitude of $b$, times the cosine of the angle between $a$ and $b$:

#### $$a \cdot b = |a||b|cos\theta_{ab}$$

This method is not very convenient unless we know each of the things on the right hand side to begin with. It would generally be used to find the angle itself. 

### Definition 1
Let's look at this in code.

In [26]:
a = np.array([1,2])
a

array([1, 2])

In [27]:
b = np.array([2,1])
b

array([2, 1])

If we wanted to use the direct definition of the dot product, we would want to loop through both arrays simultaneously, multiply each corresponding element together, and add it to the final sum. 

In [28]:
dot = 0
for e, f in zip(a,b):
    dot += e*f
dot                      # result is 4 as expected

4

Another interesting operation that you can do with numpy arrays is multiply two arrays together. We have already seen how to multiply a vector by a scalar. 

In [30]:
a * b             # element wise multiplication of a and b 

array([2, 2])

However, the above method could not be done with two arrays of different sizes. Now, if we summed the result of `a * b` we would end up with the dot product.

In [31]:
np.sum(a * b)           # this is the element wise multiplication of a and b, summed

4

An interesting thing about numpy is that the sum function is an instance method of the numpy array itself. So we could also write the above as:

In [32]:
(a * b).sum()

4

Now, while both of the above methods yield the correct answer, there is a more convenient way to calculate the dot product. Numpy comes packaged with a dot product function.

In [33]:
np.dot(a,b)

4

Like the `sum` function, the `dot` function is also an instance method of the numpy array, so we can call it on the object itself. 

In [34]:
a.dot(b)

4

This is also equivalent to:

In [35]:
b.dot(a)

4

### Definition 2
Let's now look at the alternative definition of the dot product, to calculate the angle between $a$ and $b$. For this we need figure out how to calculate the length of a vector. We can do this by taking the square root of the sum of each element squared. In other words, use pythagorean theorem.

In [37]:
amag = np.sqrt( (a * a).sum())
amag

2.23606797749979

Numpy actually has a function to do all of this work for us, since it is such a common operation. It is part of the linalg module in numpy, which also contains many other linear algebra functions. 

In [41]:
amag = np.linalg.norm(a)
amag

2.23606797749979

Now with this in hand, we are ready to calculate the angle. For clarity, the angle is defined as:

#### $$cos\theta_{ab} = \frac{a \cdot b}{|a||b|}$$

In [43]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.7999999999999998

So the cosine of the angle is 0.8, and the actual angle is the arc cosine of 0.8:

In [45]:
angle = np.arccos(cosangle)
angle

0.6435011087932847

By default this is in radians. 

---
<br></br>
# Vectors and Matrices
A numpy array has already been shown to be like a vector: we can add them, multiply them by a scalar, and perform element wise operations like `log` or `sqrt`. So what is a matrix then? Think of it as a two dimensional array.

In [51]:
M = np.array([ [1,2], [3,4] ])        # creating a matrix. 1st index is row, 2nd index is col
M

array([[1, 2],
       [3, 4]])

In [48]:
M[0][0]                      # one way of accessing values from matrix

1

In [49]:
M[0,0]                       # another shorthand way of accessing value in matrix

1

There is an actual data type in numpy called matrix as well.

In [53]:
M2 = np.matrix([ [1,2], [3,4] ])
M2

matrix([[1, 2],
        [3, 4]])

This works somewhat similarly to a numpy array, but it is not exactly the same. Most of the time we just use numpy arrays, and in fact the official documentation actually recommends not using numpy matrix. If you see a matrix, it is a good idea to convert it into an array:

In [55]:
M3 = np.array(M2)
M3

array([[1, 2],
       [3, 4]])

Note that even though this is now an array, we still have convenient matrix operations. For example if we wanted to find the transpose of M:

In [56]:
M

array([[1, 2],
       [3, 4]])

In [57]:
M.T

array([[1, 3],
       [2, 4]])

To summarize, we have shown that a matrix is really just a 2-dimensional numpy array, and a vector is a 1-dimensional numpy array. So a matrix is really like a 2 dimensional vector. The more general way to think about this is that a matrix is a 2-dimensional mathematical object that contains numbers, and a vector is a 1-dimensional mathematical object that contains numbers. 

Sometimes you may see vectors represented as a 2-d object. For example, in a math textbook a column vector may be described as (3 x 1), and a row vector (1 x 3). Sometimes we may represent them like this in numpy. 

---
<br></br>
# Generating Matrices to Work With
Sometimes we just need arrays to try stuff on, like in this course. One way to do this is to use `np.array` and pass in a list:

In [58]:
np.array([1,2,3])

array([1, 2, 3])

However, this is inconvenient since each element needs to be typed in manually. What if we wanted arrays of different sizes?

Lets start by creating a vector of zeros.

In [60]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

We can also create a 10 x 10 matrix of all zeros.

In [62]:
Z = np.zeros((10, 10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Notice that the function still takes in 1 input, a tuple containing each dimension. 

There is an equivalent function that creates an array of all ones.

In [64]:
O = np.ones((10, 10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

What if we wanted random numbers? We could use `np.random.random`.

In [66]:
R = np.random.random((10,10))
R

array([[0.85605432, 0.95303017, 0.35835843, 0.05553049, 0.50352372,
        0.79284477, 0.17307957, 0.15495916, 0.80349829, 0.52970348],
       [0.10638164, 0.18284097, 0.30309349, 0.1788535 , 0.24742533,
        0.272136  , 0.65365846, 0.99016874, 0.03743142, 0.70867619],
       [0.5760099 , 0.02431515, 0.47861786, 0.97440706, 0.19212456,
        0.28327061, 0.60635581, 0.32893627, 0.55290507, 0.48778588],
       [0.36827245, 0.68208707, 0.45807578, 0.33885551, 0.45055826,
        0.29218447, 0.78292424, 0.94594624, 0.51451056, 0.83172184],
       [0.49707746, 0.01605323, 0.98155602, 0.3577372 , 0.73105092,
        0.78708516, 0.1460198 , 0.95848855, 0.04000149, 0.23600369],
       [0.66138109, 0.464723  , 0.98781249, 0.68856559, 0.97075006,
        0.72307998, 0.69533545, 0.26475817, 0.75858351, 0.78308352],
       [0.12741335, 0.30064585, 0.37611466, 0.33238342, 0.73223474,
        0.27299646, 0.94094281, 0.57671565, 0.21255952, 0.41373889],
       [0.4744563 , 0.32919102, 0.0152936

One thing that we can quickly see is that all of these values are greater than 0 and less than 1. Whenever we talk about random numbers, you should be interested in the probability distribution that the random numbers came from. This particular random functions gives us uniformly distributed numbers between 0 and 1. What if we wanted gaussian distributed numbers? Numpy has a function for that as well.

In [68]:
# G = np.random.randn((10, 10))          this will not work, sine randn does not take tuple

G = np.random.randn(10,10)
G

array([[-0.82949821, -0.14928398, -1.82475751,  0.09717052,  1.44440614,
        -1.73805378, -0.17509296,  0.11671398,  0.76734382,  0.96697768],
       [ 1.85574181,  0.08034421,  0.00283216,  0.71701093, -1.64681207,
        -0.88526668,  1.31858469,  1.92013903,  0.18036797, -0.84131642],
       [ 0.13316877, -0.28176862, -0.47106288, -0.22776688,  1.01159741,
         0.11139526,  0.80577488,  0.49506451, -0.12006958, -0.91874854],
       [-0.59997636, -0.51426609, -0.92842242, -1.20682307, -1.38945692,
         2.06782454,  1.31045835, -0.59523498, -0.10747227,  0.50128959],
       [ 0.37753132, -0.12478803, -0.53258967, -0.26331331,  1.12904435,
        -0.89388794, -0.14424929, -1.42217404,  1.63479007, -1.53093132],
       [ 0.97070732, -0.41805953,  0.08082798,  0.4009525 ,  1.09761373,
        -0.41273791, -0.06510427, -0.25898831,  2.15479612, -0.30839871],
       [-0.73848221,  0.15326129, -1.21248259,  0.00928649,  0.10775682,
         1.18709075,  0.16362849,  1.85804224

Numpy arrays also have convenient ways for us to calculate statistics of matrices.

In [69]:
G.mean()      # gives us the mean

0.035428330826396855

In [70]:
G.var()       # gives us the variance

0.9097895080436358

---
<br></br>
# Matrix Products
When you learn about matrix products in linear algebra, you generally learn about matrix multiplication. Matrix multiplication has a special requirement, and that is that the inner dimensions of the matrices you are multiplying must match. 

For example say we have matrix `A` that is **(2, 3)** and a matrix `B` that is **(3, 3)**, we can multiply A * B, since the inner dimension is 3, however we cannot multiply B * A, since the inner dimensions are 3 and 2, hence they do not match. 

Why do we have this requirement when we multiply matrices? Well lets look at the definition of matrix multiplication:

#### $$C(i,j) = \sum_{k=1}^KA(i,k)B(k,j)$$

So the (i,j)th entry of $C$ is the sum of the multiplication of all the corresponding elements of the ith row of A and the jth column of B. In other words, C(i,j) is the dot product of the ith row of A and the jth column of B. Because of this, we actually use the `dot` function in numpy! That does what we recognize as matrix multiplication! 

A very natural thing to want to do, both in math and in computing, is element by element multiplication! 

#### $$C(i,j) = A(i,j) * B(i,j)$$

For vectors, we already saw that an asterisk `*` operation does this. As you may have guessed, for 2-d arrays, the asterisk also does element wise multiplication. That means that when you use the `*` on multidimensional arrays, both of them have to be the exact same size. This may seem odd, since in other languages, the asterisk does mean real matrix multiplication. So we just need to remember that in numpy, the asterisk `*` does mean element by element multiplication, and the `dot` means matrix multiplication. 

Another thing that is odd is that when we are writing down mathematical equations, there isn't even a well defined symbol for element wise multiplication. Sometimes researchers use a circle with a dot inside of it, sometimes they use a circle with an x inside of it. But there does not seem to be a standard way to do that in math. 

---
<br></br>
# More Matrix Operations

The dot product is often referred to as the **inner product**. But we can also look at the **outer product**. An outer product is going to a be a **column vector** times a **row vector**. An inner product is going to a be a **row vector** times a **column vector**. For more information on this checkout my linear algebra walk through in the math appendix. 

In [71]:
a = np.array([1,2])
a

array([1, 2])

In [73]:
b = np.array([3,4])
b

array([3, 4])

Lets first look at the dot product:

In [76]:
np.dot(a,b)

11

Now the inner product:

In [77]:
np.inner(a,b)

11

We see that it is the same as the dot product. Now let's look at the outer product:

In [78]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

We can get the same result if we ensure that out `a` and `b` are proper matrices, and then use the dot product. Note, here we see the equivalence to the `inner` and `outer` methods above. 

In [105]:
a = np.array([[1,2]])
a

array([[1, 2]])

In [106]:
b = np.array([[3,4]])
b

array([[3, 4]])

In [107]:
b = b.T
b

array([[3],
       [4]])

In [109]:
np.dot(a,b)

array([[11]])

In [110]:
np.dot(b,a)

array([[3, 6],
       [4, 8]])